package com.xebyte.core;

import java.util.*;
import java.util.regex.Pattern;

/**
 * Centralized naming convention validation for Ghidra MCP tools.
 * All methods return warnings (empty list = valid). Tools apply changes and include warnings in response.
 */
public final class NamingConventions {

    private NamingConventions() {}

    // -----------------------------------------------------------------------
    // Function name validation
    // -----------------------------------------------------------------------

    private static final Set<String> ALLOWED_VERBS = Set.of(
            "Get", "Set", "Is", "Has", "Can", "Find", "Create", "Initialize", "Process",
            "Validate", "Calculate", "Build", "Parse", "Update", "Check", "Handle",
            "Load", "Save", "Free", "Allocate", "Deallocate", "Register", "Unregister",
            "Clear", "Reset", "Resolve", "Lookup", "Dispatch", "Invoke", "Apply",
            "Add", "Remove", "Delete", "Insert", "Append", "Prepend",
            "Open", "Close", "Start", "Stop", "Enable", "Disable",
            "Read", "Write", "Send", "Receive", "Connect", "Disconnect",
            "Lock", "Unlock", "Acquire", "Release",
            "Compute", "Convert", "Format", "Encode", "Decode", "Compress", "Decompress",
            "Sort", "Filter", "Search", "Count", "Measure",
            "Draw", "Render", "Paint", "Blit", "Fill",
            "Notify", "Signal", "Trigger", "Fire", "Emit",
            "Mark", "Flag", "Tag", "Log", "Report", "Dump",
            "Test", "Verify", "Assert", "Compare", "Match",
            "Spawn", "Kill", "Destroy", "Cleanup", "Shutdown", "Abort",
            "Compile", "Link", "Bind", "Map", "Unmap",
            "Push", "Pop", "Enqueue", "Dequeue", "Peek",
            "Increment", "Decrement", "Adjust", "Clamp", "Scale",
            "Iterate", "Traverse", "Walk", "Scan", "Enumerate",
            "Assign", "Copy", "Clone", "Move", "Swap", "Merge",
            "Show", "Hide", "Toggle", "Select", "Deselect",
            "Attach", "Detach", "Mount", "Unmount",
            "Accept", "Reject", "Cancel", "Retry", "Skip"
    );

    private static final Pattern PASCAL_CASE = Pattern.compile("^[A-Z][a-zA-Z0-9]+$");
    private static final Pattern MODULE_PREFIX = Pattern.compile("^[A-Z]+_[A-Z].*");
    private static final int MIN_FUNCTION_NAME_LENGTH = 8;

    /**
     * Validate a function name against conventions. Returns list of warnings (empty = valid).
     * Thunks/imports with underscores are exempt.
     */
    public static List<String> validateFunctionName(String name, boolean isThunk) {
        if (name == null || name.isEmpty()) return List.of();
        // Thunks/imports are exempt (e.g., _DllMain@12, Ordinal_10024)
        if (isThunk) return List.of();
        // Auto-generated names are not validated (they'll get the auto_name deduction)
        if (ServiceUtils.isAutoGeneratedName(name)) return List.of();

        List<String> warnings = new ArrayList<>();

        // Strip UPPERCASE_ module prefix if present (e.g., DATATBLS_CompileTxtDataTable -> CompileTxtDataTable)
        // Module prefixes are valid and match original source code conventions.
        String mainName = name;
        if (MODULE_PREFIX.matcher(name).matches()) {
            int underscoreIdx = name.indexOf('_');
            mainName = name.substring(underscoreIdx + 1);
        }

        if (!PASCAL_CASE.matcher(mainName).matches()) {
            warnings.add("Function name '" + name + "' — main part '" + mainName + "' is not PascalCase. Expected: " + toPascalCase(mainName));
        }

        // Check for non-prefix underscores in the main part
        if (mainName.contains("_")) {
            warnings.add("Function name '" + name + "' — main part '" + mainName + "' contains underscores. Use PascalCase after the module prefix.");
        }

        if (mainName.length() < MIN_FUNCTION_NAME_LENGTH) {
            warnings.add("Function name '" + name + "' is too short (main part '" + mainName + "' is " + mainName.length() + " chars, minimum " + MIN_FUNCTION_NAME_LENGTH + ").");
        }

        // Extract first word (verb) from PascalCase main part
        String firstWord = extractFirstPascalWord(mainName);
        if (firstWord != null && !ALLOWED_VERBS.contains(firstWord)) {
            warnings.add("Function name '" + name + "' does not start with a recognized verb. First word '" + firstWord + "' not in allowed list. Common verbs: Get, Set, Initialize, Process, Calculate, Find, Check, Handle");
        }

        return warnings;
    }

    // -----------------------------------------------------------------------
    // Variable Hungarian notation validation
    // -----------------------------------------------------------------------

    /** Map of Hungarian prefix -> required type patterns */
    private static final Map<String, Set<String>> PREFIX_TO_TYPES = Map.ofEntries(
            Map.entry("b", Set.of("byte", "bool", "uchar", "undefined1")),
            Map.entry("c", Set.of("char", "byte", "uchar")),
            Map.entry("f", Set.of("bool", "byte", "BOOL")),
            Map.entry("n", Set.of("int", "short", "long", "undefined2", "undefined4")),
            Map.entry("dw", Set.of("uint", "dword", "ulong", "DWORD", "undefined4")),
            Map.entry("w", Set.of("ushort", "word", "WORD", "undefined2")),
            Map.entry("l", Set.of("long", "int")),
            Map.entry("fl", Set.of("float", "undefined4")),
            Map.entry("d", Set.of("double", "undefined8")),
            Map.entry("ll", Set.of("longlong", "undefined8")),
            Map.entry("qw", Set.of("ulonglong", "undefined8")),
            Map.entry("h", Set.of("HANDLE", "void *", "uint", "dword")),
            Map.entry("sz", Set.of("char *", "char[", "string")),
            Map.entry("lpsz", Set.of("char *", "char[", "string")),
            Map.entry("lpcsz", Set.of("char *", "char[", "string")),
            Map.entry("wsz", Set.of("wchar_t *", "wchar_t[", "wchar16 *"))
    );

    /**
     * Validate that a variable name's Hungarian prefix matches its type.
     * Returns a warning string if mismatched, null if OK.
     */
    public static String validateHungarianPrefix(String name, String typeName) {
        if (name == null || typeName == null) return null;
        // Skip auto-generated names (local_*, param_*, *Var*)
        if (name.startsWith("local_") || name.startsWith("param_") || name.matches(".*Var\\d+")) return null;
        // Skip phantom/artifact names
        if (name.startsWith("extraout_") || name.startsWith("in_")) return null;

        boolean isPointer = typeName.contains("*") || typeName.contains("[");
        String prefix = extractHungarianPrefix(name);
        if (prefix == null) return null; // No recognizable prefix

        // Pointer prefixes
        if (prefix.equals("p") || prefix.equals("pp") || prefix.startsWith("p") && Character.isUpperCase(name.charAt(prefix.length()))) {
            if (prefix.equals("pp")) {
                if (!typeName.contains("**")) {
                    return "Variable '" + name + "' has pp prefix (double pointer) but type is '" + typeName + "'";
                }
                return null;
            }
            // Single pointer prefix (p, pb, pw, pdw, pn)
            if (!isPointer) {
                return "Variable '" + name + "' has pointer prefix '" + prefix + "' but type is '" + typeName + "' (not a pointer)";
            }
            return null;
        }

        // Scalar prefixes
        Set<String> allowedTypes = PREFIX_TO_TYPES.get(prefix);
        if (allowedTypes != null) {
            boolean matches = false;
            for (String allowed : allowedTypes) {
                if (typeName.startsWith(allowed) || typeName.equals(allowed)) {
                    matches = true;
                    break;
                }
            }
            if (!matches && !isPointer) {
                return "Variable '" + name + "' has prefix '" + prefix + "' which requires type in " + allowedTypes + " but actual type is '" + typeName + "'";
            }
        }

        return null;
    }

    // -----------------------------------------------------------------------
    // Global naming validation
    // -----------------------------------------------------------------------

    /**
     * Validate a global name has g_ prefix with Hungarian notation.
     */
    public static List<String> validateGlobalName(String name) {
        List<String> warnings = new ArrayList<>();
        if (name == null || name.isEmpty()) return warnings;
        if (name.startsWith("DAT_") || name.startsWith("s_")) return warnings; // Auto-generated, not validated

        if (!name.startsWith("g_")) {
            warnings.add("Global '" + name + "' missing g_ prefix. Expected: g_" + name);
        }
        return warnings;
    }

    // -----------------------------------------------------------------------
    // Label naming validation
    // -----------------------------------------------------------------------

    private static final Pattern SNAKE_CASE = Pattern.compile("^[a-z][a-z0-9]*(_[a-z0-9]+)*$");

    /**
     * Validate a label name uses snake_case.
     */
    public static List<String> validateLabelName(String name) {
        List<String> warnings = new ArrayList<>();
        if (name == null || name.isEmpty()) return warnings;
        if (name.startsWith("LAB_")) return warnings; // Auto-generated, not validated

        if (!SNAKE_CASE.matcher(name).matches()) {
            warnings.add("Label '" + name + "' is not snake_case. Expected format: loop_process_items, err_null_pointer");
        }
        return warnings;
    }

    // -----------------------------------------------------------------------
    // Plate comment structure validation
    // -----------------------------------------------------------------------

    /**
     * Validate plate comment has required sections. Returns list of warnings.
     */
    public static List<String> validatePlateCommentStructure(String plateComment) {
        List<String> warnings = new ArrayList<>();
        if (plateComment == null || plateComment.isEmpty()) return warnings;

        String[] lines = plateComment.split("\n");
        boolean hasAlgorithm = false;
        boolean hasParameters = false;
        boolean hasReturns = false;

        for (String line : lines) {
            String trimmed = line.trim();
            if (trimmed.startsWith("Algorithm:") || trimmed.equals("Algorithm")) hasAlgorithm = true;
            if (trimmed.startsWith("Parameters:") || trimmed.equals("Parameters")) hasParameters = true;
            if (trimmed.startsWith("Returns:") || trimmed.equals("Returns")) hasReturns = true;
        }

        if (!hasAlgorithm) warnings.add("Plate comment missing Algorithm section");
        if (!hasParameters) warnings.add("Plate comment missing Parameters section");
        if (!hasReturns) warnings.add("Plate comment missing Returns section");

        return warnings;
    }

    // -----------------------------------------------------------------------
    // Enum member validation
    // -----------------------------------------------------------------------

    private static final Pattern UPPER_SNAKE_CASE = Pattern.compile("^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$");

    /**
     * Validate an enum member name uses UPPERCASE_SNAKE_CASE.
     */
    public static List<String> validateEnumMemberName(String name) {
        List<String> warnings = new ArrayList<>();
        if (name == null || name.isEmpty()) return warnings;

        if (!UPPER_SNAKE_CASE.matcher(name).matches()) {
            warnings.add("Enum member '" + name + "' is not UPPERCASE_SNAKE_CASE. Expected format: PLAYER_TYPE, MAX_COUNT");
        }
        return warnings;
    }

    // -----------------------------------------------------------------------
    // Struct field auto-prefix
    // -----------------------------------------------------------------------

    /** Type name -> required Hungarian prefix mapping for auto-fix */
    private static final Map<String, String> TYPE_TO_PREFIX = Map.ofEntries(
            Map.entry("byte", "b"), Map.entry("uchar", "b"), Map.entry("bool", "f"), Map.entry("BOOL", "f"),
            Map.entry("char", "c"),
            Map.entry("int", "n"), Map.entry("short", "n"), Map.entry("long", "n"),
            Map.entry("uint", "dw"), Map.entry("dword", "dw"), Map.entry("ulong", "dw"), Map.entry("DWORD", "dw"),
            Map.entry("ushort", "w"), Map.entry("word", "w"), Map.entry("WORD", "w"),
            Map.entry("float", "fl"),
            Map.entry("double", "d"),
            Map.entry("longlong", "ll"),
            Map.entry("ulonglong", "qw")
    );

    /**
     * Auto-fix a struct field name to include the correct Hungarian prefix based on its type.
     * If the name already has the correct prefix, returns it unchanged.
     * If the name has no prefix or the wrong prefix, prepends the correct one.
     *
     * Examples:
     *   ("count", "uint") -> "dwCount"
     *   ("dwCount", "uint") -> "dwCount" (already correct)
     *   ("next", "void *") -> "pNext"
     *   ("pNext", "void *") -> "pNext" (already correct)
     *   ("Field04", "undefined4") -> "dwField04" (undefined4 defaults to dw)
     */
    public static String autoFixFieldPrefix(String fieldName, String typeName) {
        if (fieldName == null || fieldName.isEmpty() || typeName == null) return fieldName;

        // Determine the correct prefix for this type
        String correctPrefix;
        boolean isPointer = typeName.contains("*") || typeName.contains("[");
        if (isPointer) {
            // Pointer types get 'p' prefix
            correctPrefix = "p";
        } else {
            correctPrefix = TYPE_TO_PREFIX.get(typeName);
            if (correctPrefix == null) {
                // undefined4 -> dw, undefined2 -> w, undefined1 -> b
                if (typeName.equals("undefined4")) correctPrefix = "dw";
                else if (typeName.equals("undefined2")) correctPrefix = "w";
                else if (typeName.equals("undefined1")) correctPrefix = "b";
                else if (typeName.equals("undefined8")) correctPrefix = "qw";
                else return fieldName; // Unknown type, don't modify
            }
        }

        // Check if the field already has the correct prefix
        String existingPrefix = extractHungarianPrefix(fieldName);
        if (existingPrefix != null && existingPrefix.equals(correctPrefix)) {
            return fieldName; // Already correct
        }

        // Check if field already starts with a different known prefix — strip it first
        if (existingPrefix != null) {
            // Wrong prefix — strip it and re-prefix
            String baseName = fieldName.substring(existingPrefix.length());
            return correctPrefix + baseName;
        }

        // No prefix — add one. Capitalize first letter of the name.
        if (Character.isUpperCase(fieldName.charAt(0))) {
            return correctPrefix + fieldName;
        } else {
            return correctPrefix + Character.toUpperCase(fieldName.charAt(0)) + fieldName.substring(1);
        }
    }

    // -----------------------------------------------------------------------
    // Type validation
    // -----------------------------------------------------------------------

    /**
     * Check if a type change is from undefined to undefined (no improvement).
     */
    public static boolean isUndefinedToUndefined(String oldType, String newType) {
        return oldType != null && newType != null
                && oldType.startsWith("undefined") && newType.startsWith("undefined");
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /** Extract the first PascalCase word from a name like "GetPlayerHealth" -> "Get" */
    static String extractFirstPascalWord(String name) {
        if (name == null || name.isEmpty() || !Character.isUpperCase(name.charAt(0))) return null;
        StringBuilder word = new StringBuilder();
        word.append(name.charAt(0));
        for (int i = 1; i < name.length(); i++) {
            if (Character.isUpperCase(name.charAt(i))) break;
            word.append(name.charAt(i));
        }
        return word.length() > 1 ? word.toString() : null;
    }

    /** Extract Hungarian prefix from a variable name like "dwFlags" -> "dw", "pUnit" -> "p" */
    static String extractHungarianPrefix(String name) {
        if (name == null || name.length() < 2) return null;

        // Multi-char prefixes first (order matters: longer prefixes before shorter)
        String[] multiPrefixes = {"lpcsz", "lpsz", "wsz", "pp", "pb", "pw", "pdw", "pn", "pfn",
                "sz", "dw", "fl", "ll", "qw", "ld", "ab", "aw", "ad", "an"};
        for (String prefix : multiPrefixes) {
            if (name.startsWith(prefix) && name.length() > prefix.length()
                    && Character.isUpperCase(name.charAt(prefix.length()))) {
                return prefix;
            }
        }

        // Single-char prefixes
        char first = name.charAt(0);
        if ("bcfnwhld".indexOf(first) >= 0 && name.length() > 1 && Character.isUpperCase(name.charAt(1))) {
            return String.valueOf(first);
        }

        // Pointer prefix: p followed by uppercase (pUnit, pGame)
        if (first == 'p' && name.length() > 1 && Character.isUpperCase(name.charAt(1))) {
            return "p";
        }

        // Global prefix: g_ followed by Hungarian
        if (name.startsWith("g_") && name.length() > 3) {
            String afterG = name.substring(2);
            String innerPrefix = extractHungarianPrefix(afterG);
            return innerPrefix != null ? "g_" + innerPrefix : null;
        }

        return null;
    }

    /** Attempt to convert a string to PascalCase */
    static String toPascalCase(String name) {
        if (name == null || name.isEmpty()) return name;
        // Handle underscore-separated (SKILLS_GetLevel -> SkillsGetLevel)
        StringBuilder result = new StringBuilder();
        for (String part : name.split("_")) {
            if (!part.isEmpty()) {
                result.append(Character.toUpperCase(part.charAt(0)));
                if (part.length() > 1) result.append(part.substring(1).toLowerCase());
            }
        }
        return result.toString();
    }
}
